version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    image: "tekana-v2-app"
    restart: on-failure
    ports:
      - "2025:2025"
    environment:
      HOST: app:2025
      PORT: 2025
      DATABASE_URL: postgresql://POSTGRES_USER:POSTGRES_PASSWORD@postgres_db:5432/POSTGRES_DB
      NODE_ENV: production
    depends_on:
      - postgres_db
      - redis_caches
    networks:
      - tekana-v2-networks

  postgres_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=POSTGRES_DB
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: ["postgres", "-c", "max_connections=200", "-c", "timezone=Etc/UTC", "-c", "default_text_search_config=pg_catalog.english"]
    ports:
      - "15433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - tekana-v2-networks

  redis_cache:
    container_name: redis_caches
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      -  tekana-v2-networks
    ports:
      - "6379:6379"

volumes:
  postgres_data:

networks:
  tekana-v2-networks:
    driver: bridge